    FROM python:3.9-slim

    WORKDIR /app

    COPY pyproject.toml poetry.lock /app/

    RUN pip install poetry && poetry install --no-root

    COPY data src/serve/api.py .

    EXPOSE 44933

    CMD ["poetry", "run", "dvc", "pull", "-r", "origin", "-f", "&&", "poetry", "run", "python", "src/serve/api.py"]