FROM python:3.9-slim

COPY . .

RUN pip install poetry && poetry install --no-root

EXPOSE 5000

CMD ["poetry", "run", "dvc", "pull", "-r", "origin", "-f"] 
CMD ["poetry", "run", "python", "src/serve/api.py"]
