version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_API
    ports:
      - "5000:5000"
    command: sh -c "poetry run dvc pull -r origin -f && poetry run python src/serve/api.py"
    networks:
      - airpredict_network

  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    networks:
      - airpredict_network
      
networks:
  airpredict_network:
    driver: bridge