name: Fetch Data Pipeline
on:
  push:

jobs:
  fetch_btc_data:
    runs-on: ubuntu-latest

    outputs:
      sha_new: ${{steps.sha_new.outputs.SHA_NEW}}

    permissions:
      contents: write

    strategy:
      matrix:
        python-version: [ "3.9" ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: fetch_btc_data
        run: poetry run python src/data/fetch_data.py

      - name: Git global
        run: git config --global user.email "alen.gojkosek@student.um.si" && git config --global user.name "alengojkosek"
        
      - name: Git global
        run: poetry run dvc config core.autostage true

      - name: Commit data
        run: |
            git add data/raw/raw_data.csv.dvc data/raw/.gitignore && git commit -m'Add new raw dataset'
            poetry run dvc add data/raw/raw_data.csv
            
      - name: Push data dvc
        run: poetry run dvc push -r origin

      - name: Push changes git
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}

      - name: Get commit SHA and store it in GITHUB_OUTPUT
        id: sha_new
        run: echo "SHA_NEW=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"